export const cardData = [
  {
    src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvr-vFCFEekjw91mws1FQ6lNHg8G1Wu4Z74g&usqp=CAU",
    alt: "part",
    title: "Air Bag",
    LastModified: "20 days ago",
    created: "11 month ago",
  },
  {
    src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvr-vFCFEekjw91mws1FQ6lNHg8G1Wu4Z74g&usqp=CAU",
    alt: "part",
    title: "Car",
    LastModified: "10 days ago",
    created: "12 month ago",
  },
  {
    src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvr-vFCFEekjw91mws1FQ6lNHg8G1Wu4Z74g&usqp=CAU",
    alt: "part",
    title: "Air Bag",
    LastModified: "10 days ago",
    created: "1 month ago",
  },
  {
    src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvr-vFCFEekjw91mws1FQ6lNHg8G1Wu4Z74g&usqp=CAU",
    alt: "part",
    title: "Air Bag",
    LastModified: "40 days ago",
    created: "1 month ago",
  },
  {
    src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvr-vFCFEekjw91mws1FQ6lNHg8G1Wu4Z74g&usqp=CAU",
    alt: "part",
    title: "Lever",
    LastModified: "10 days ago",
    created: "4 month ago",
  },
  {
    src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvr-vFCFEekjw91mws1FQ6lNHg8G1Wu4Z74g&usqp=CAU",
    alt: "part",
    title: "Air Bag",
    LastModified: "60 days ago",
    created: "1 month ago",
  },
  {
    src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvr-vFCFEekjw91mws1FQ6lNHg8G1Wu4Z74g&usqp=CAU",
    alt: "part",
    title: "Screw",
    LastModified: "10 days ago",
    created: "1 month ago",
  },
  {
    src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvr-vFCFEekjw91mws1FQ6lNHg8G1Wu4Z74g&usqp=CAU",
    alt: "part",
    title: "Air Bag",
    LastModified: "10 days ago",
    created: "9 month ago",
  },
  {
    src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvr-vFCFEekjw91mws1FQ6lNHg8G1Wu4Z74g&usqp=CAU",
    alt: "part",
    title: "Exhaust",
    LastModified: "12 days ago",
    created: "1 month ago",
  },
  {
    src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvr-vFCFEekjw91mws1FQ6lNHg8G1Wu4Z74g&usqp=CAU",
    alt: "part",
    title: "Air Bag",
    LastModified: "10 days ago",
    created: "1 month ago",
  },
  {
    src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvr-vFCFEekjw91mws1FQ6lNHg8G1Wu4Z74g&usqp=CAU",
    alt: "part",
    title: "Vent",
    LastModified: "10 days ago",
    created: "1 month ago",
  },
  {
    src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvr-vFCFEekjw91mws1FQ6lNHg8G1Wu4Z74g&usqp=CAU",
    alt: "part",
    title: "Air Bag",
    LastModified: "10 days ago",
    created: "7 month ago",
  },
  {
    src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvr-vFCFEekjw91mws1FQ6lNHg8G1Wu4Z74g&usqp=CAU",
    alt: "part",
    title: "Air Bag",
    LastModified: "16 days ago",
    created: "1 month ago",
  },
  {
    src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvr-vFCFEekjw91mws1FQ6lNHg8G1Wu4Z74g&usqp=CAU",
    alt: "part",
    title: "Sunroof",
    LastModified: "10 days ago",
    created: "3 month ago",
  },
  {
    src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvr-vFCFEekjw91mws1FQ6lNHg8G1Wu4Z74g&usqp=CAU",
    alt: "part",
    title: "Air Bag",
    LastModified: "90 days ago",
    created: "2 month ago",
  },
];
